### ISSUE TITLE
Zmiana daty przy wykresach.

### ISSUE THREAD

**Issue by syntaxerro** [skalagi/pogoda-cli#13]
URL: `//weatherapi.skalagi.pl/day-charts/outTemp.json?date=2016-03-01`
Byłoby miło, gdyby input date był tylko w trybie dziennym. 
W miesięcznym wypadałoby zrobić nawigację między samymi miesiącami, a w rocznym latami.

**Comment by rascada** [comment]
https://github.com/skalagi/pogoda-cli/commit/016a45a64a165b64729a88946dc77c1f9c944059
