### ISSUE TITLE
Dodawanie subskrybcji email.

### ISSUE THREAD

**Issue by syntaxerro** [skalagi/pogoda-cli#3]
Route: `/subsribe`
Metoda: `POST`
Parametr: `email=example@example.com`
Nagłówek: `application/x-www-form-urlencoded`

Wyświetl komunikat w zależności od odpowiedzi.

**Comment by rascada** [comment]
na pewno "subsribe"?

**Comment by syntaxerro** [comment]
ta

**Comment by rascada** [comment]
a jednak subscribe

**Comment by syntaxerro** [comment]
Brakuje mi jeszcze jakiegoś placeholder z `Wpisz adres email` czy coś takiego. W teorii ktoś może nie wiedzieć co znaczy `Subskrypcja pocztowa`.

BTW. Jak chcesz zmieniać napis na przycisku jeśli user jest już zapisany to pod `/subscriber-exists` wysyłasz takiego samego POSTa i zwraca `true` (jeśli jest zapisany) albo `false`.

**Comment by rascada** [comment]
a no fakt, po enterze normalnie waliduje że to nie email i nie puszcza, ale zapomniałem o tej walidacji jak podpinałem przycisk (bo to paper-button, a nie submit)
